name: arcgis_maps_sdk_flutter_samples
description: "Sample code demonstrating the capabilities of ArcGIS Maps SDK for Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  arcgis_maps: ^300.0.0
  arcgis_maps_toolkit: ^300.0.0
  async: ^2.12.0
  build: ^2.4.2
  build_config: ^1.1.2
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  flutter_localizations:
    sdk: flutter
  flutter_syntax_view: ^4.1.7
  flutter_tts: 4.2.3
  glob: ^2.1.3
  go_router: ^16.1.0
  http: ^1.3.0
  intl: ^0.20.2
  markdown: ^7.3.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  simple_html_css: ^5.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/category_images/
